# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Pre-Release

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1.3.0
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - uses: marvinpinto/action-automatic-releases@latest
      with:
        title : Automatic Latest Pre-release
        automatic_release_tag: pre-release
        repo_token: ${{secrets.repo_token}}
        prerelease: true
        files: |
          ./build/libs/*.jar
          ./build/distributions/*
